"""Compatibility facade for :mod:`PyHydroGeophysX.workflows.em1d`."""

from PyHydroGeophysX._internal.deprecations import warn_legacy_path
from PyHydroGeophysX.workflows.em1d import (
    BackendUnavailable,
    DEFAULT_FDEM,
    DEFAULT_INVERSION,
    DEFAULT_MODEL,
    DEFAULT_TDEM,
    METHODS,
    TEMCOMPANY_MOMENTS,
    backend_status,
    build_em_config,
    calibrate_to_reference,
    estimate_data_scale,
    example_catalog,
    fdem_forward,
    fdem_invert,
    invert_line,
    is_temcompany_source,
    is_ttem_source,
    load_line_geometry,
    load_sounding,
    load_temcompany_sounding,
    load_ttem_sounding,
    model_arrays,
    model_depth_profile,
    save_inversion,
    tdem_forward,
    tdem_invert,
    tdem_joint_invert,
)

warn_legacy_path("PyHydroGeophysX.em1d", "PyHydroGeophysX.workflows.em1d")

__all__ = [
    "BackendUnavailable",
    "METHODS",
    "TEMCOMPANY_MOMENTS",
    "DEFAULT_MODEL",
    "DEFAULT_FDEM",
    "DEFAULT_TDEM",
    "DEFAULT_INVERSION",
    "backend_status",
    "example_catalog",
    "model_arrays",
    "model_depth_profile",
    "is_temcompany_source",
    "is_ttem_source",
    "load_temcompany_sounding",
    "load_ttem_sounding",
    "load_sounding",
    "load_line_geometry",
    "fdem_forward",
    "tdem_forward",
    "fdem_invert",
    "tdem_invert",
    "tdem_joint_invert",
    "estimate_data_scale",
    "calibrate_to_reference",
    "invert_line",
    "build_em_config",
    "save_inversion",
]
