"""Deterministic Python generation from a workflow recipe."""

from __future__ import annotations

from pathlib import Path
from pprint import pformat

from .models import WorkflowSpec, iter_artifact_refs
from .registry import get_workflow


_SCRIPT_TEMPLATE = '''"""Generated by PyHydroGeophysX from workflow {workflow_id}."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from PyHydroGeophysX.workflows import RunContext, WorkflowSpec, run_workflow


SPEC_DATA = {spec_literal}


def main() -> int:
    parser = argparse.ArgumentParser(description="Run PyHydroGeophysX workflow {workflow_id}.")
    parser.add_argument("--project-root", type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument("--output-dir", type=Path, default=Path(__file__).resolve().parent / "results")
    args = parser.parse_args()
    spec = WorkflowSpec.from_dict(SPEC_DATA)
    result = run_workflow(
        spec,
        RunContext(project_root=args.project_root, output_dir=args.output_dir),
    )
    print(json.dumps(result.to_dict(), indent=2, sort_keys=True))
    return 0 if result.status in {{"ok", "completed", "success"}} else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def generate_python(spec: WorkflowSpec, path: str | Path) -> Path:
    """Generate a standalone, editable script using only the public workflow API."""
    descriptor = get_workflow(spec.workflow_id)
    spec.validate(stochastic=descriptor.stochastic)
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    literal = pformat(spec.to_dict(), sort_dicts=True, width=100)
    absolute_paths = sorted({
        ref.path for ref in iter_artifact_refs((spec.inputs, spec.parameters))
        if Path(ref.path).is_absolute()
    })
    portability_note = ""
    if absolute_paths:
        lines = "\n".join(f"# - {path}" for path in absolute_paths)
        portability_note = (
            "# PORTABILITY WARNING: these external artifacts use absolute paths:\n"
            f"{lines}\n\n"
        )
    destination.write_text(
        portability_note
        + _SCRIPT_TEMPLATE.format(workflow_id=spec.workflow_id, spec_literal=literal),
        encoding="utf-8",
    )
    return destination


__all__ = ["generate_python"]
