name: Build and Deploy Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx==7.1.2
        pip install sphinx-rtd-theme==1.3.0
        pip install myst-parser==2.0.0
        pip install nbsphinx==0.9.1
        pip install sphinx-copybutton==0.5.2
        pip install sphinx-gallery==0.14.0
        pip install numpy scipy matplotlib tqdm
        pip install --no-deps -e .

    - name: Build documentation
      run: |
        cd docs
        sphinx-apidoc -f -o source/api ../PyHydroGeophysX
        sphinx-build -b html source build/html

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        force_orphan: true
